version: "3.4"

services:
  erigon:
    build: .
    container_name: erigon
    environment:
      RUN_ARGS: "--config=/config/erigon.yaml --metrics --metrics.addr=0.0.0.0"
    ports:
      - 8545:8545/tcp
      - 8551:8551/tcp
      - 6060:6060/tcp
    networks:
      - shared
    volumes:
      - ./config/${network:-mainnet}:/config
      - "${host_data_dir:-erigon-data}:/data"
    restart: unless-stopped

networks:
  shared:

volumes:
  erigon-data:
