version: 1.9.16
latest_release_url: https://api.github.com/repos/ava-labs/avalanchego/releases/latest
cli_help: --help
example_config: 'https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/docs/nodes/maintain/avalanchego-config-flags.md

  https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/docs/nodes/maintain/chain-config-flags.md

  https://raw.githubusercontent.com/ava-labs/avalanche-docs/master/docs/nodes/maintain/subnet-configs.md

  '
example_metrics: 127.0.0.1:9650/ext/metrics
